version: "2.1"

jobs:
    repack-bottle:
      docker:
       - image: thoughtmachine/please_ubuntu:20190226
      steps:
       - checkout
       - run:
           name: Build
           command: ./pleasew run //:release_bottles -- --github_token $GITHUB_TOKEN

workflows:
  version: 2
  bottle-all:
    jobs:
      - repack-bottle:
          filters:
            branches:
              only: master
