version: "2.1"

jobs:
    repack-bottle:
      docker:
       - image: thoughtmachine/please_ubuntu:20190226
      steps:
       - add_ssh_keys:
           fingerprints:
             - "fc:5b:1e:b2:a7:00:25:07:b2:84:78:e0:12:e8:74:6b"
       - checkout
       - run:
           name: Build
           command: ./pleasew run -p //:release_bottles -- --github_token $GITHUB_TOKEN

workflows:
  version: 2
  bottle-all:
    jobs:
      - repack-bottle:
          filters:
            branches:
              only: master
